[package]
name = "faucet"
version = "0.1.0"
authors = ["Ian Macalinao <ian@aptos.is>"]
license = "Apache-2.0"

[readme]
title = "Aptosis Devnet Faucet"

[addresses]
faucet = "0x6fdf5c5cf431d5db75b2b53f0df8aa6687056d47ea7a588e9c512dd2b7a810a8"
AptosisMinter = "0xd21e5c6e363a5ae4815ac7ef8e08301f36a8af54c08481c2ce3cb137ef28ff80"

[dependencies.mint_wrapper]
git = "https://github.com/aptosis/mint-wrapper.git"
rev = "eedd56a2fbac1e2bbe2ee377fe2bbaece94b573d"

[dependencies.deployer]
git = "https://github.com/DeployDAO/aptos-deployer.git"
rev = "8d863c9e28dd0744b8013b7799387faabbb0a286"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"
